config/routes.rb
Rails.application.routes.draw do
  resources :stories do
    resources :comments
  end

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/login'  => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  root 'stories#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, presence: true

  belongs_to :story
  belongs_to :created_by, class_name: "User"
end

app/models/story.rb
class Story < ApplicationRecord
  validates :email, presence: true
  validates :url_link, format: { with: /\A(https|http)/ }
  has_many :comments

  belongs_to :created_by, class_name: "User"

  def can_this_user_edit?(user)
    created_by == user
  end

  def can_this_user_destroy?(user)
    created_by == user
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :comments
  has_many :stories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def logged_in?
    !!current_user
  end
  helper_method :logged_in?

  def authorize!
    redirect_to login_path unless logged_in?
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # GET /comments
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  def show
    @comment = Comment.find(params[:id])
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  def create
    @story = Story.find(params[:story_id])
    @comment = @story.comments.create(comment_params)
    @comment.created_by = current_user

    @comment.save

    redirect_to story_path(@story)
  end

  # PATCH/PUT /comments/1
  def update
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      redirect_to @comment, notice: 'Comment was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /comments/1
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to comments_url, notice: 'Comment was successfully destroyed.'
  end

  private
    # Only allow a trusted parameter "white list" through.
    def comment_params
      params.require(:comment).permit(:story_id, :body)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:email]
    password = params[:password]

    user = User.find_by(email: email)

    if user && user.authenticate(password)
      session[:user_id] = user.id
      flash[:notice] = user.name + " is now logged on to the Iron News"

      redirect_to root_path
    else
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil

    redirect_to root_path
  end

end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :authorize!, except: [:index]

  # GET /stories
  def index
    @stories = Story.all.order(created_at: :desc).page params[:page]
  end

  # GET /stories/1
  def show
    @story = Story.find(params[:id])
    @comment = Comment.find_by(params[:story_id])
  end

  # GET /stories/new
  def new
    @story = Story.new
  end

  # GET /stories/1/edit
  def edit
    @story = Story.find(params[:id])

    unless @story.can_this_user_edit?(current_user)
      redirect_to stories_path, notice: 'You may not edit other users posts.'
      return
    end
  end

  # POST /stories
  def create
    @story = Story.new(story_params)
    @story.created_by = current_user

    if @story.save
      redirect_to @story, notice: 'Story was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /stories/1
  def update
    @story = Story.find(params[:id])

    unless @story.can_this_user_edit?(current_user)
      redirect_to stories_path, notice: 'You may not edit other users posts.'
      return
    end

    if @story.update(story_params)
      redirect_to @story, notice: 'Story was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /stories/1
  def destroy
    @story = Story.find(params[:id])

    unless @story.can_this_user_destroy?(current_user)
      redirect_to stories_path, notice: 'You may not delete other users posts.'
    else
      @story.destroy
      redirect_to stories_url, notice: 'Story was successfully destroyed.'
    end
  end

  private
  # Only allow a trusted parameter "white list" through.
  def story_params
    params.require(:story).permit(:title, :url_link, :email)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to root_path
    else
      redirect_to signup_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @comment.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h4>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
          <%= f.label :story_id, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.number_field :story_id, class: "form-control" %>
      </div>
      </div>
  <div class="form-group">
          <%= f.label :body, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_area :body, class: "form-control" %>
      </div>
      </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end -%>

app/views/comments/_show.html.erb
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Story</th>
        <th>Body</th>
      </tr>
    </thead>

    <tbody class="table-body">
      <%- @comments.each do |comment| %>
      <tr>
        <td><%= comment.story_id %></td>
        <td><%= comment.body %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/comments/edit.html.erb
<div class="page-header">
  <%= link_to comments_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @comment, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing comment</h1>
</div>

<%= render 'form' %>

app/views/comments/index.html.erb
<div class="page-header">
  <%= link_to new_comment_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Comment
  <% end %>
  <h1 Listing>comments</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Story</th>
        <th>Body</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody class="table-body">
      <%- @comments.each do |comment| %>
      <tr>
        <td><%= comment.story_id %></td>
        <td><%= comment.body %></td>
        <td>
          <%= link_to comment do %>
            <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
          <% end %>
        </td>
        <td>
          <%= link_to edit_comment_path(comment) do %>
            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
          <% end %>
        </td>
        <td>
          <%= link_to comment, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/comments/new.html.erb
<div class="page-header">
  <%= link_to comments_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New comment</h1>
</div>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>
    <%= Rails.application.class.parent_name %>
  </title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/css?family=Josefin+Sans:600" rel="stylesheet">
</head>
<body class="controller-<%= controller_name%> action-<%= action_name%>">
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
          <div class="navbar-brand">
            <%= link_to "The Iron Yard News", stories_path %>
          </div>
      </div>
      <div id="navbar" class="collapse navbar-collapse pull-right">
        <ul class="nav navbar-nav">
          <li><%= link_to "Create New Story", new_story_path %></li>
          <% if logged_in? %>
            <li>
              <p class="navbar-text">Hello <%= current_user.name %></p>
            </li>
            <li>
              <%= link_to "Logout", logout_path %>
            </li>
          <% else %>
            <li>
              <%= link_to 'Login', login_path %>
            </li>
            <li>
              <%= link_to 'Sign Up', signup_path %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>


  <nav class="navbar navbar-default navbar-fixed-bottom">
    <div class="container-fluid">
      <h5 class="text-center">&copy; 2017 The Iron Yard<a href="mailto:admin@theironnews.com" class="footer" >&nbsp;&nbsp;admin@theironnews.com</a></h5>
    </div>
  </nav>

</body>
</html>

app/views/stories/_form.html.erb
<%= form_for(@story, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @story.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@story.errors.count, "error") %> prohibited this story from being saved:</h4>

      <ul>
      <% @story.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :title, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :url_link, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :url_link, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :email, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :email, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-inverse" %>
    </div>
  </div>
<% end -%>

app/views/stories/edit.html.erb
<div class="page-header well well-sm">
  <%= link_to stories_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-hand-left"></span>
    &nbsp;Back
  <% end %>
  <%= link_to @story, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-comment"></span>
    &nbsp;Comments
  <% end %>
  <h1>Editing story</h1>
</div>

<%= render 'form' %>

app/views/stories/index.html.erb
<div class="well">
  <div class="media-left">
    <div class="media-object">
      <%= image_tag("tiy_logo_1.png", size: "100") %>
    </div>
  </div>
  <div class="media-body">
    <h1 class="pull-right">The Iron Stories</h1>
  </div>
</div>

<div class="table-responsive">
  <% @stories.each.with_index do |story, index| %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <span class="badge"><%= index + 1 %></span>
        &nbsp;<%= link_to story.title, story.url_link %>
        <div class="pull-right">
          <%= link_to story do %>
          <div class="badge">Comments <%= story.comments.count %></div>
          <% end %>
        </div>
      </div>
      <div class="panel-body row">
        <%= story.created_by.email %>
        <div class="pull-right">
          Created about <%= time_ago_in_words(story.created_at) %> ago
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="well well-sm text-center">
  <div><%= paginate @stories %></div>
  <div><%= page_entries_info @stories %></div>
</div>

app/views/stories/new.html.erb
<div class="page-header well well-sm">
    <%= link_to stories_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-hand-left"></span>
    &nbsp;Back
    <% end %>
  <h1>New Story</h1>
</div>

<%= render 'form' %>

app/views/stories/show.html.erb
<div class="page-header well well-sm">
  <%= link_to stories_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-hand-left"></span>
    &nbsp;Back
  <% end %>
  <%= link_to edit_story_path(@story), class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    &nbsp;Edit
  <% end %>
  <%= link_to @story, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-trash"></span>
    &nbsp;Delete
  <% end %>
  <h1>Story Comments</h1>
</div>

<dl class="jumbotron dl-horizontal">
  <h3>
    <dt>Title:</dt>
    <dd><%= link_to @story.title, @story.url_link %></dd>

    <dt>Url link:</dt>
    <dd><%= link_to @story.url_link, @story.url_link %></dd>

    <dt>Email:</dt>
    <dd><%= @story.email %></dd>
  </h3>
</dl>

<h2>Comments</h2>
  <% @story.comments.each do |comment| %>
    <p>
      <strong><%= comment.created_by.name %>: </strong>
      <%= comment.body %>
    </p>
  <% end %>

<h2>Add a comment:</h2>
  <%= form_for([@story, @story.comments.build]) do |f| %>
    <p>
      <%= f.label :body %><br>
      <%= f.text_field :body, class: "form-control" %>
    </p>
    <p>
      <%= f.submit class: "btn btn-inverse"%>
    </p>
  <% end %>

app/views/users/new.html.erb
<div class="page-header">
  <h1>Signup &mdash; The Iron News</h1>
</div>

<%= form_for(@user, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :email, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :email, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :password, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.password_field :password, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.password_field :password_confirmation, class: "form-control" %>
    </div>
  </div>
  <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>